#!/bin/bash

source .env

message=$1

git add .
git commit -m "$message"
git push

sshpass -p $SERVER_KEY ssh -t root@128.199.12.79 "\
  cd projects/acessando &&\
  source ~/.zshrc &&\
  git pull &&\
  pm2 restart acessando --update-env
"%  